name: Bundling & Publishing
on: [push]
jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup node with yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn
      - name: Bundle via Webpack (Preact CLI)
        run: yarn build
      - name: Enable Server-Side Routing
        run: mv "build/index.html" "build/404.html"
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}